### ISSUE TITLE
How to get the best result from multiple estimated results (cornerGroups/marker)?

### ISSUE THREAD

**Issue by BobbleLaw** [bbenligiray/stag#13]
Hi, Thank you for your work.

When I tried to use stag in my project, I found that each candidate marker would give multiple estimated results (most of the time four) which are almost identical. e.g. two markers in the sight, eight poses return. From your paper, I guess that is to ensure the detection stability when occlusion happens. My questions would be, how can I get only one result for each candidate marker. Should I use average, or there're some other evaluation metrics you suggested to get the best estimation.

**Comment by bbenligiray** [comment]
Hey @BobbleLaw , please refer to https://github.com/bbenligiray/stag/issues/8

For a quick fix, I would pick a random one among the four.
