### ISSUE TITLE
STag dependencies

### ISSUE THREAD

**Issue by jakubchojnacki-digica** [bbenligiray/stag#26]
Hi,

Would you mind sharing the exact dependencies used in the project?
OpenCV version, OS version, compiler etc.

**Comment by bbenligiray** [comment]
Hi. IIRC I was using OpenCV 3.1 (3.1.0?), Windows 7, the compiler was MSVC but I have no recollection of the exact version/parameters. I didn't do a very good job of documenting all that, sorry.

**Comment by jakubchojnacki-digica** [comment]
It really helped. Thank you @bbenligiray
