### ISSUE TITLE
License

### ISSUE THREAD

**Issue by manuelvolk** [bbenligiray/stag#3]
Hi Burak,

thank you for the great paper and for providing the code here. 
Do you plan to add a license to your implementation? 

Best,

Manuel

**Comment by bbenligiray** [comment]
Hi Manuel,

My co-authors and I have not yet decided whether to provide an open source license. It is very much a possibility and I will update this repo ASAP if it happens.

Burak

**Comment by HardTaskToFindAName** [comment]
Hallo Burak,

thank you for the answer. I'm highly interested in using your results  and also want to contribute some features (python wrapper, rosnode). But without a license it may never can be used by others. Therefore, I'm looking forward what your decision is in terms of license. 

Best,

Manuel

**Comment by hocjordan** [comment]
Hi Burak,

Just following up on this, what did you decide to do regarding the licence?

Best,
Harry

**Comment by bbenligiray** [comment]
Alright alright :grin: 
https://github.com/bbenligiray/stag/blob/master/LICENSE
