### ISSUE TITLE
Compiler

### ISSUE THREAD

**Issue by impet14** [bbenligiray/stag#4]
Hi all,

Thanks very much for the contribution of the great works. Could I ask, what the compiler you use for compile this project and what is the os?

Thank you!
Sincerely,

**Comment by bbenligiray** [comment]
Hi,

I used Windows and MSVC. I don't recall using any platform-specific functionality, so I expect it to compile as is for most cases.

However, note that the feature extraction parts are omitted at the moment, so the code won't compile. Full code will be released upon publication.

**Comment by impet14** [comment]
Thanks, I look forward to the full version.

**Comment by bbenligiray** [comment]
All sources released.
