### ISSUE TITLE
missing  files "ED/EDLines.h" and "ED/EdgeMap.h"

### ISSUE THREAD

**Issue by lupin982** [bbenligiray/stag#5]
Hi,
very great job, i'm trying to compile your source code on windows, but it seems missing two files:
#include "ED/EDLines.h"
#include "ED/EdgeMap.h"

**Comment by bbenligiray** [comment]
Hi,

Currently, they are left out in purpose, and the code won't compile without them.

I am going to update and close this issue when they are added.

**Comment by bobbycho** [comment]
Aren't you ready to add those header files?
Thanks

**Comment by bbenligiray** [comment]
All sources are added, the code compiles and runs fine now.
